# Generated by Django 6.0.5 on 2026-10-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mynotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
